telegram_token: Telegram bot token
telegram_workers: Number of threads
telegram_all_burst_limit: 30
telegram_all_time_limit_ms: 1000
telegram_group_burst_limit: 20
telegram_group_time_limit_ms: 60000
telegram_read_timeout: 20
telegram_connect_timeout: 5
telegram_known_sources:
  - e621.net
  - furaffinity.net
  - furrynetwork.com
  - cloudfront.net
  - twitter.com
  - twimg.com
  - weasyl.com

mongo_uri: Mongo URI
