telegram_token: Telegram bot token
telegram_workers: Number of threads
telegram_all_burst_limit: 30
telegram_all_time_limit_ms: 1000
telegram_group_burst_limit: 20
telegram_group_time_limit_ms: 60000
telegram_read_timeout: 20
telegram_connect_timeout: 5
telegram_known_sources:
  - e621.net
  - furaffinity.net
  - furrynetwork.com
  - cloudfront.net
  - twitter.com
  - twimg.com
  - weasyl.com

reverse_search_limit: 400
reverse_search_limit_h: 24
reverse_search_pressure_s: 900
reverse_search_max_concurrency: 8
reverse_search_max_concurrency_per_chat: 2

mongo_uri: Mongo URI
